language: java

jdk:
- openjdk8
- openjdk11

# skip the Travis-CI install phase because Maven handles that directly
install:
- 'true'
# everything below here can be removed when the libsodium dependency goes away
- echo "installing libsodium"
- curl https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz | tar xvz -C ../
- pushd ../libsodium-1.0.18
- ./configure
- make
- sudo make install
- popd

script:
- "./mvnw verify -Pci -V -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

after_success:
- bash <(curl -s https://codecov.io/bash) -f coverage/target/site/jacoco-aggregate/jacoco.xml
