language: java

jdk:
- openjdk8
- openjdk11

# skip the Travis-CI install phase because Maven handles that directly
install:
- 'true'

script:
- "./mvnw package -Pci -V -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

after_success:
- bash <(curl -s https://codecov.io/bash) -f coverage/target/site/jacoco-aggregate/jacoco.xml
